modLoader="javafml"
loaderVersion="[38,)"
license="MIT License"

[[mods]]
modId="everydesc"
version="1.0"
displayName="Everything Descriptions"
credits=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/everything-descriptions"
authors="Kuraion"
logoFile="logo.png"
description=''''''

[[dependencies.everydesc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,]"
    ordering="NONE"
    side="BOTH"




